name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## RocketBootstrap v$RESOLVED_VERSION

  ### Changes
  $CHANGES

  ### Compatibility
  - iOS 13.0 – 16.5 (rootless jailbreak)
  - Architecture: arm64 + arm64e

categories:
  - title: Bug Fixes
    labels: [bug, fix]
  - title: New Features
    labels: [enhancement, feature]
  - title: Maintenance
    labels: [chore, refactor]

version-resolver:
  major:
    labels: [breaking]
  minor:
    labels: [enhancement, feature]
  patch:
    labels: [bug, fix, chore]
  default: patch
